# Generated by Django 2.1.7 on 2019-04-15 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190415_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
