# Generated by Django 2.0.4 on 2019-03-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('organization_unit', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('algorithm', models.CharField(max_length=200)),
                ('CRL_name', models.CharField(max_length=200)),
                ('valid_period', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
