# Generated by Django 2.0.4 on 2019-03-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0002_auto_20190322_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='author',
        ),
    ]
