# Generated by Django 2.0.4 on 2019-03-26 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0004_ca_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('valid_period', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=1000)),
                ('public_key', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
