# Generated by Django 2.0.4 on 2019-03-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0005_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='private_key',
            field=models.CharField(max_length=10000),
        ),
    ]
