# Generated by Django 2.0.4 on 2019-03-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0006_auto_20190327_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CA',
            new_name='Company',
        ),
    ]
