# Generated by Django 2.0.4 on 2019-03-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0007_auto_20190328_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='CRL_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='valid_period',
        ),
    ]
