# Generated by Django 2.0.4 on 2019-03-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genkey', '0009_auto_20190329_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='organization_unit',
        ),
    ]
