# Generated by Django 2.1.7 on 2019-04-17 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.DateTimeField()),
                ('organization', models.CharField(max_length=200)),
                ('organization_unit', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('algorithm', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=10000)),
                ('public_key', models.CharField(max_length=1000)),
                ('pem', models.CharField(max_length=10000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
